### ISSUE TITLE
c/c++ 代码的头文件include 会显示不全 

### ISSUE THREAD

**Issue by ZiqingYip** [soulhighwing/LocalGPT#1]
挺好用的，感谢开源出来分享~  反馈使用中遇到的一个关于代码内容显示的小问题：当返回结果中有 c/c++ 代码，#include 后半部分的文件名会丢失。

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/3692379/229263132-6874712e-b2ea-40f9-bab3-4e55efd35f38.png">

感觉可能是跟 <> 转义字符的处理有关，本想动手修复并提个PR，但过程中发现对前端这块的基础还是过于薄弱，一时找不到解决的头绪，所以先提了个 issue 。辛苦 repo主 方便的时候帮忙看下。

**Comment by soulhighwing** [comment]
谢谢，已经更新修复。
